using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZDAT
{
    public enum OP
    {
        Customer = 106,
        OrderNum = 109,
        Qty = 36,
        Available = 39,
        BO = 75,
        OnOrder = 118,
        Product = 37,
        Price = 53,
        Desc = 120,
        NTS = 124,
        Stock = 41,
        SO = 42,
        DS = 43,
        Supplier = 45,
        SuppName = 46,
        ProdCode = 48,
        Add = 152,
        NewItem = 150,
        NotesCharges = 136,
        Delete = 151,
        Repeat = 153,
        Memo = 144,
        Inquiry = 145,
        Order = 146,
        Save = 149,
        Clear = 179,
        Close = 154,
        OrderHeader = 114,
        ShipToNum = 93,
        ShipToDesc = 91,
        ShipToOvr = 90,
        LineIncr = 18
        //EDIData = 4,
        //EDINotes = 3
    }

    public enum OH
    {
        Customer = 106,
        OrderNum = 108,
        SoldTo = 125,
        ShipToDesc = 126,
        ShipToNum = 12,
        OrderPad = 121,
        CustomerPO = 39,
        JobNumber = 40,
        EdiPO = 51,
        ShipTerms = 76,
        ShipTermsDesc = 79,
        ShipVia = 77,
        ShipViaDesc = 80,
        ShipAcctNum = 89,
        ShipInstruc = 78,
        Memo = 143,
        Inquiry = 144,
        Order = 145,
        Save = 116,
        Clear = 117,
        Close = 124
    }

    public enum OS
    {
        ByItem = 2,
        itmCatalogNum = 3,
        itmCustPartNum = 4,
        itmSIMNum = 6,
        itmNoneOfAbove = 7,
        ByOrder = 16,
        ordCustPONum = 8,
        ordOrderedBy = 9,
        ordQuotedTo = 10,
        ordJobNumber = 11,
        ordInsideSales = 12,
        ordOutsideSales = 13,
        ordInvoiceNum = 14,
        ordNoneOfAbove = 15,
        fltrCustFrom = 18,
        fltrCustTo = 21,
        fltrShipFrom = 25,
        fltrShipTo = 27,
        fltrItemSchShipDateFrom = 31,
        fltrItemSchShipDateTo = 33,
        fltrItemReqDateFrom = 37,
        fltrItemReqDateTo = 39,
        fltrOrdDateFrom = 43,
        fltrORdDateTo = 45,
        ClearFilterBy = 47,
        otypeAll = 50,
        otypeNormal = 51,
        otypeShipComplete = 52,
        otypeAssembleHold = 53,
        otypeShippedType = 54,
        ordsAll = 55,
        ordsOrders = 56,
        ordsInquiries = 57,
        ordsCreditMemo = 58,
        ordsMemos = 59,
        ordsOrdersInquiries = 60,
        ordsOrdersCreditMemo = 61,
        ostatusAll = 62,
        ostatusOpen = 63,
        ostatusClosed = 64,
        shipstatAll = 65,
        shipstatNotPicked = 66,
        shipstatPicked = 67,
        sipstatShipped = 68,
        shipstatInvoiced = 69,
        Search = 70,
        Clear = 71,
        CLose = 72
    }

    public enum OSR
    {
        OrderGrid = 2,
        OrderNum = 13,
        Cycle = 15,
        OrderStatus = 17,
        OrderType = 19,
        OrderedBy = 25,
        QuotedTo = 64,
        ShipTerms = 32,
        ShipTermsDesc = 34,
        ShipVia = 33,
        ShipViaDesc = 35,
        InSales = 42,
        OutSales = 43,
        CustPO = 21,
        JobNum = 23,
        CreatedBy = 45,
        InvoiceNum = 27,
        Type = 18,
        OrderTotal = 56,
        Supplier = 60,
        Customer = 6,
        CustomerDesc = 7,
        ViewRemoteOrder = 124,
        ViewRemotePO = 125,
        ViewReplCost = 126,
        ProductNotes = 128,
        ViewPO = 129,
        ViewOrder = 130,
        ManageOrder = 131,
        ShippingActivity = 132,
        NewSearch = 133,
        Close = 134,
        CustPartNum = 136,
        SIMNum = 65,
        ContractNo = 229,
        CurPrice = 224,
        LocalInventoryDesc = 110,
        Summary = 135
    }
}
